name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    environment: build
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1

      - name: Replace versions
        run: bash replace-version.sh ${{ steps.tagName.outputs.tag }}

      - name: Setup env
        shell: cmd
        run: move tools\MPQEditor.ini %APPDATA%

      - name: Pack
        run: bash pack.sh

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Make Changelog.html
        run: npx markdown-to-html-cli@3.5.3 -s CHANGELOG.md -o ./dest/CHANGELOG.html --style=./public/style.css --no-dark-mode

      - name: Zip mpq file
        uses: TheDoctor0/zip-release@0.6.0
        with:
          directory: './dest/'
          path: './lang-zh.mpq'
          type: 'zip'
          filename: 'Release.zip'

      - name: Release Zip file
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dest/Release.zip
          bodyFile: "CHANGELOG.md"

      - name: Setup ossutil
        uses: yizhoumo/setup-ossutil@v1.1.3
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET }}

      - name: Upload dest to oss
        run: |
          ossutil cp -f dest/Release.zip oss://${{ secrets.OSS_BUCKET }}/
          ossutil cp -f dest/CHANGELOG.html oss://${{ secrets.OSS_BUCKET }}/
          ossutil cp -f public/index.html oss://${{ secrets.OSS_BUCKET }}/
          ossutil cp -f public/favicon.png oss://${{ secrets.OSS_BUCKET }}/

      - name: Commit CHANGELOG.md
        run: |
          git config --local user.email "github-actions[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "Bump CHANGELOG.md"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master