name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      
      - name: pack
        run: bash pack.sh
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          directory: './dest/'
          path: './lang-zh.mpq'
          type: 'zip'
          filename: 'Release.zip'

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./dest/Release.zip
          bodyFile: "CHANGELOG.md"