name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      
      - name: Get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1
      
      - name: pack
        run: bash pack.sh
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          directory: './dest/'
          path: './lang-zh.mpq'
          type: 'zip'
          filename: 'Release.zip'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: Release v${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dest/Release.zip
          asset_name: MedianXL-Chinese-v${{ steps.tagName.outputs.tag }}.zip
          asset_content_type: application/zip
